Develop
SnakCat/CoinAPI pull request #1
Opened 2023-12-27 15:53 UTC by SnakCat

<img width="362" alt="DZCoin" src="https://github.com/SnakCat/CoinAPI/assets/121857982/29a97ee7-1e32-48cd-b053-6e84dbe69067">

2023-12-28 15:53 UTC, mishamorochko requested changes
Все ок, надо исправить коммент и убрать сепаратор в таблице

2023-12-28 15:53 UTC, mishamorochko commented on CoinAPI/ModelCoin.swift
> +    let volume_1day_usd: Double
Для нейминга стоит использовать CamelCase, чтобы задать кастовый ключ необходимо использовать CodingKeys внутри структуры

2023-12-28 17:42 UTC, SnakCat commented
Все исправил

2023-12-29 08:38 UTC, mishamorochko approved these changes

2023-12-29 09:02 UTC, merged